# Part of this code was generated by ChatGPT in Jan 2025

##############
############## GENERATE DATA
##############

rm(list=ls())
set.seed(1988)
library(mice)

# generate fake data
n <- 100                     # Number of observations
c <- 0.2                    # Proportion of missing values
X <- rnorm(n, mean = 5, sd = 2)  # Predictor
beta0 <- 2                   # True intercept
beta1 <- 1.5                  # True slope
epsilon <- rnorm(n, mean = 0, sd = 1)  # Error term
Y <- beta0 + beta1 * X + epsilon        # Outcome variable

# introduce missingness in Y
missing_indices <- sample(1:n, size = n * c, replace = FALSE)
Y[missing_indices] <- NA  # 20% missing values

# combine data into a data frame
data <- data.frame(X = X, Y = Y)
head(data)

##############
############## PERFORM MCMC IMPUTATION
##############

imputed_data <- mice(data, 
                    m = 5, 
                    method = "norm", 
                    seed = 1988)

##############
############## REGRESSION ON COMPLETED DATASET
##############

models <- with(imputed_data, lm(Y ~ X))

##############
############## PRINT RESULTS
##############

summary(pool(models))
